version: "3.8"

services:
  deployhub_worker:
    image: deployhub_worker
    build:
      context: .
      dockerfile: Dockerfile.worker
    env_file:
      - .env
    volumes:
      - ~/.docker:/root/.docker
      - ~/.config/gcloud/application_default_credentials.json:/secrets/gcp/adc.json:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /secrets/gcp/adc.json
      CLOUDSDK_CORE_PROJECT: ${GCLOUD_PROJECT_ID}
      REDIS_URL: redis:6379
    depends_on:
      - redis

  api:
    image: deployhub_api
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file:
      - .env
    volumes:
      - ~/.config/gcloud/application_default_credentials.json:/secrets/gcp/adc.json:ro
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /secrets/gcp/adc.json
      CLOUDSDK_CORE_PROJECT: ${GCLOUD_PROJECT_ID}
      REDIS_URL: redis:6379
    ports:
      - "8080:8080"
    depends_on:
      - redis

  deployhub_frontend:
    image: deployhub_frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"

  redis:
    image: redis:alpine
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
