version: "3.8"

services:
  deployhub_worker:
    image: deployhub_worker
    build:
      context: .
      dockerfile: Dockerfile.worker
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env:ro
      - ~/.config/gcloud/application_default_credentials.json:/secrets/gcp/adc.json:ro
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /secrets/gcp/adc.json
      REDIS_URL: redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis

  api:
    image: deployhub_api
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env:ro
      - ~/.config/gcloud/application_default_credentials.json:/secrets/gcp/adc.json:ro
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /secrets/gcp/adc.json
      REDIS_URL: redis:6379
    ports:
      - "8080:8080"
    depends_on:
      - redis

  deployhub_frontend:
    image: deployhub_frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - api

  redis:
    image: redis:alpine
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
