FROM gcr.io/kaniko-project/executor:latest AS kaniko
FROM golang:1.25
WORKDIR /app

COPY --from=kaniko /kaniko /kaniko
ENV PATH=$PATH:/kaniko

COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN GOOS=linux go build -o /worker-server ./cmd/worker

CMD ["/worker-server"]
